from src.models.analysis_result import AnalysisResult
import requests
import json

class LocalAIExplainer:
    """
    Deterministic template engine that selects and fills explanation templates 
    based on the AnalysisResult fields. Guarantees no hallucination and no cloud dependency.
    """
    
    def __init__(self, use_llm: bool = True, model_name: str = "llama3"):
        self.use_llm = use_llm
        self.model_name = model_name
        self.ollama_url = "http://localhost:11434/api/generate"
        self.disclaimer = (
            "This explanation was generated by a local LLM based on "
            "deterministic rule outputs. It does not constitute medical advice, legal opinion, or a "
            "determination of regulatory violation. All findings should be reviewed "
            "by qualified clinical and compliance staff."
        )
        
        # Mapping rule IDs to human readable names for templates
        self.rule_names = {
            "R1_MOBILITY_SUPPRESSION": "Mobility Suppression",
            "R2_CONFINEMENT_SIGNAL": "Confinement Signal",
            "R3_SEDENTARY_SPIRAL": "Sedentary Spiral",
            "R4_CAREGIVER_OVERDEPENDENCE": "Caregiver Overdependence",
            "R5_ALERT_SUPPRESSION_EFFECT": "Alert Suppression Effect"
        }
        
        # Mapping rule IDs to regulation references for templates
        self.rule_refs = {
            "R1_MOBILITY_SUPPRESSION": "CMS §483.25(h)",
            "R2_CONFINEMENT_SIGNAL": "CMS §483.10(e)(1)",
            "R3_SEDENTARY_SPIRAL": "CMS §483.25(h)",
            "R4_CAREGIVER_OVERDEPENDENCE": "CMS §483.12(a)(2)",
            "R5_ALERT_SUPPRESSION_EFFECT": "NIST AI RMF"
        }

    def _get_comma_separated(self, rule_ids: list[str], mapping: dict) -> str:
        # Deduplicate while preserving order
        items = list(dict.fromkeys([mapping.get(rid, rid) for rid in rule_ids]))
        if not items: return ""
        if len(items) == 1: return items[0]
        if len(items) == 2: return f"{items[0]} and {items[1]}"
        return ", ".join(items[:-1]) + f", and {items[-1]}"

    def _generate_with_ollama(self, prompt: str) -> str:
        try:
            payload = {
                "model": self.model_name,
                "prompt": prompt,
                "stream": False
            }
            # Increased timeout to 60s for older laptops loading models into memory
            response = requests.post(self.ollama_url, json=payload, timeout=60)
            response.raise_for_status()
            return response.json().get("response", "").strip()
        except requests.exceptions.RequestException as e:
            # Fall back to empty string to trigger deterministic fallback
            print(f"\n[DEBUG] Ollama connection failed: {e}\n")
            return ""

    def generate_explanation(self, result: AnalysisResult) -> dict:
        """
        Translates a fully computed AnalysisResult into a structured human language response.
        If use_llm is True and Ollama is available, dynamically writes the explanation.
        Otherwise falls back to deterministic templates.
        """
        explanation = ""
        insights = []
        
        rule_names_str = self._get_comma_separated(result.triggered_rules, self.rule_names)
        rule_refs_str = self._get_comma_separated(result.triggered_rules, self.rule_refs)

        # 1. Explanation Templates / LLM Generation
        if self.use_llm:
            prompt = (
                f"You are a clinical compliance AI assistant. A resident has been analyzed "
                f"with the status '{result.status}'. Triggered behavioral rules: {rule_names_str}. "
                f"Regulatory concerns: {rule_refs_str}. "
                f"Write a 3-sentence professional summary explaining what this means. "
                f"Do NOT make legal conclusions. Do NOT give medical advice. Just state the facts "
                f"based on these behavioral indicators."
            )
            # Try LLM
            llm_text = self._generate_with_ollama(prompt)
            if llm_text:
                explanation = llm_text
                
        # Fallback to deterministic if LLM failed or is disabled
        if not explanation:
            if result.status == "no_issue":
                explanation = (
                    "No behavioral indicators of restraint-effect patterns were detected for "
                    "this resident during the analysis window. Mobility, autonomy, and dignity "
                    "sub-scores are within normal range. No clinical review is recommended at this time."
                )
            elif result.status == "monitor":
                if result.ambiguous_cause:
                    explanation = (
                        "A mobility decline was detected without a corresponding alert event or "
                        "increased caregiver burden. This pattern may reflect a health-related "
                        "change rather than a monitoring-induced restraint effect. Clinical review "
                        "is recommended to determine the underlying cause before escalating."
                    )
                else:
                    explanation = (
                        f"One behavioral indicator was detected that may warrant observation: "
                        f"{rule_names_str}. This pattern is consistent with early-stage monitoring "
                        f"concerns under {rule_refs_str}. Clinical staff should review care notes "
                        f"for this resident over the next 7 days."
                    )
            elif result.status == "review_recommended":
                explanation = (
                    f"Multiple behavioral indicators of potential restraint-effect patterns were detected: "
                    f"{rule_names_str}. These patterns may be consistent with CMS least-restrictive care "
                    f"concerns under {rule_refs_str}. A formal compliance review is recommended. This "
                    f"system does not determine whether a violation has occurred."
                )

        # 2. Workflow Insights
        triggered = set(result.triggered_rules)
        
        if "R1_MOBILITY_SUPPRESSION" in triggered:
            insights.append("Consider scheduling a mobility assessment with physical therapy to establish an updated functional baseline.")
        if "R2_CONFINEMENT_SIGNAL" in triggered:
            insights.append("Review whether the resident's daily schedule includes opportunities for movement outside their primary room.")
        if "R3_SEDENTARY_SPIRAL" in triggered:
            insights.append("Evaluate whether the fall-monitoring alert sensitivity can be adjusted to reduce unnecessary movement restriction.")
        if "R4_CAREGIVER_OVERDEPENDENCE" in triggered:
            insights.append("Assess whether caregiver assistance level matches the resident's current functional capacity — over-assistance may reduce independence.")
        if "R5_ALERT_SUPPRESSION_EFFECT" in triggered:
            insights.append("Review the alert type introduced on the trigger date and assess whether it may be creating fear-of-movement behavior.")
            
        if result.ambiguous_cause:
            insights.append("No alert event was detected. Consult with nursing staff and review medical records to rule out acute health changes before attributing this pattern to monitoring behavior.")
            
        insights.append("Document this analysis in the resident's care plan review for compliance record-keeping purposes.")

        return {
            "explanation": explanation,
            "workflow_insights": insights,
            "disclaimer": self.disclaimer,
            "ai_generated": True
        }
